---
title: "Cyriac_draft"
output: html_notebook
---

This is the function that plots the output graph in the shiny app

```{r}

library(ggplot2)
library(dplyr)
library (CyCyFns)

data_to_plot <- globalaverage(data_all)
p <- ggplot(data = data_to_plot,
       aes(x = milestone_km, y = mean_time)
          ) +
     geom_point() +
     geom_smooth() +
     labs(x = "Distance run", y = "Time since departure")
p
```

This is the function that plots the average speed of the whole population of runners vs top 10% vs bottom 20%

```{r}

library(ggplot2)
library(dplyr)
library (CyCyFns)

data_to_plot <- rbind(globalaverage(data_all),
                      top10percentmean(data_all),bottom20percentmean(data_all))

p <- ggplot(data = (data_to_plot),
        aes(x = milestone_km, y = mean_time, color = Label)) +
      geom_point() +
      geom_smooth() +
      labs(x = "Distance run", y = "Time since departure")
p
```

```{r}

library(ggplot2)
library(dplyr)
library (CyCyFns)

data_to_plot <- demographics_filter(data_all, age = 42, gender = "M", nationality = "USA")

data_to_plot <- rbind(globalaverage(data_to_plot),
                      top10percentmean(data_to_plot),bottom20percentmean(data_to_plot))

p <- ggplot(data = (data_to_plot),
        aes(x = milestone_km, y = mean_time, color = Label)) +
      geom_point() +
      geom_smooth() +
      labs(x = "Distance run", y = "Time since departure")
p

```

