---
title: "FunctionTrialCodes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Trial Codes For Functions To Test if They Work

You'll find the list of functions being built here before being transformed to the proper package files


## 1. Age Bracket Column Creation
```{r}

library(dplyr)
data_all <- readRDS("data_all.rds")
data_all_dup <- data_all

View(data_all)


#inefficient code, also if statements do not support vectorized input hence need for lapply, no optimised
agebracket <- function(X){
  if (X < 20){
    Y <- "<20"
  } else
    if (20 <= X & X < 25){
      Y <- "20 - 24"
    }
    else
    if (25 <= X & X < 30){
      Y <- "25 - 29"
    }
    else
    if (30 <= X & X < 35){
      Y <- "30 - 34"
    }
    else
    if (35 <= X & X < 40){
      Y <- "35 - 39"
    }
    else
    if (40 <= X & X < 45){
      Y <- "40 - 44"
    }
    else
    if (45 <= X & X < 50){
      Y <- "45 - 49"
    }
    else
    if (50 <= X & X < 55){
      Y <- "50 - 54"
    }
    else
    if (55 <= X & X < 60){
      Y <- "55 - 59"
    }
    else
    if ( X > 60){
      Y <- "> 60"
    }
 print(return(Y))
}

#inefficient code
agebracket2 <- function(age){
  ifelse (age < 20, Y <- "<20",
    ifelse (age < 25, Y <- "20 - 24",
      ifelse (age < 30, Y <- "25 - 29",
        ifelse (age < 35, Y <- "30 - 34",
          ifelse (age < 40, Y <- "35 - 39",
            ifelse (age < 45, Y <- "40 - 44",
              ifelse (age < 50, Y <- "45 - 49",
                ifelse (age < 55, Y <- "50 - 54",
                  ifelse (age < 60, Y <- "55 - 59", Y <- "> 60")))))))))
                          
 print(return(Y))
}

#function to create age brackets based on input value of age
agebracket3 <- function(age){
  ifelse (age < 20, "<20",
    ifelse (age < 25, "20 - 24",
      ifelse (age < 30, "25 - 29",
        ifelse (age < 35, "30 - 34",
          ifelse (age < 40, "35 - 39",
            ifelse (age < 45, "40 - 44",
              ifelse (age < 50, "45 - 49",
                ifelse (age < 55, "50 - 54",
                  ifelse (age < 60, "55 - 59", "> 60")))))))))
}
#testing
agebracket2(22)
agebracket(55)
a <- agebracket3(98)
a
A <- c(1, 50, 23)
B <- lapply(A, agebracket3)
C <- agebracket3(A)
is.vector(C)




#Function to create a new column
agebracketcol <- function(X){
  X["Age_Bracket"] <- X["Age"] %>% agebracket3() %>% as.vector()
  return(X)
}

#testing on duplicated dataset
data_all_dup <- data_all_dup %>% agebracketcol()
unique(data_all_dup$`Age_Bracket`)
View(data_all_dup)
```

## 1. Age Filter - filter data based on input value of age and its corresponding age bracket
```{r}
agefilter <- function(age, dataset){ #input value of age, dataset is the data to be filtered
  agebracket <- age %>% agebracket3()
  dataset <- dataset %>% filter(Age_Bracket == agebracket)
  return(dataset)
}
#mannual testing
ageb <- (29 %>% agebracket3())
data_all_dup_age_29 <- data_all_dup %>% filter(Age_Bracket==ageb)

#testing the function
data_all_dup_age_29 <- agefilter(29, data_all_dup)
unique(data_all_dup_age_29$Age_Bracket)
View(data_all_dup_age_29)
dim(data_all_dup_age_29)

```
## 1. Overal demographics filter - filter data based on input value of age, gender & nationality
```{r}
#function that deals with missing arguments without breaking
#function broken for unknown reasons, modified below
demographics_filter <- function(dataset, age, gender, nationality){ #demographic data, dataset = raw data
  ifelse(missing(age), 
         ifelse(missing(gender),
                ifelse(missing(nationality),
                       dataset,
                       dataset %>% filter(Country == nationality)),
                ifelse(missing(nationality),
                       dataset %>% filter(M.F == gender),
                       dataset %>% filter(Country == nationality, M.F == gender))),
         
         ifelse(missing(gender),
                ifelse(missing(nationality),
                       dataset %>% filter(Age == age),
                       dataset %>% filter(Age == age, Country == nationality)),
                ifelse(missing(nationality),
                       dataset %>% filter(Age == age, M.F == gender),
                       dataset %>% filter(Age == age, Country == nationality, M.F == gender)))
  )
}
#verified that the ifelse+missing nesting works as expected, not sure why the filter function is not working properly from above
demographics_filter2 <- function(dataset, age, gender, nationality){ #demographic data, dataset = raw data
  ifelse(missing(age), 
         ifelse(missing(gender),
                ifelse(missing(nationality),
                       1,
                       2),
                ifelse(missing(nationality),
                       3,
                      4)),
         
         ifelse(missing(gender),
                ifelse(missing(nationality),
                       5,
                       6),
                ifelse(missing(nationality),
                       7,
                       8))
  )
}
#function still not working, wanna die
demographics_filter3 <- function(dataset, age=NULL, gender=NULL, nationality=NULL){ #demographic data, dataset = raw data
  case_when(
      !age==NULL & !gender == NULL & !nationality==NULL ~ dataset,
      
       age==NULL & !gender == NULL & !nationality==NULL ~ dataset %>% filter(Age == age),
       age==NULL &  gender == NULL & !nationality==NULL ~ dataset %>% filter(Age == age, M.F == gender),
       age==NULL &  gender == NULL &  nationality==NULL ~ dataset %>% filter(Age == age, M.F == gender, Country == nationality),
       age==NULL & !gender == NULL &  nationality==NULL ~ dataset %>% filter(Age == age, Country == nationality),
       
      !age==NULL &  gender == NULL & !nationality==NULL ~ dataset %>% filter(M.F == gender),
      !age==NULL &  gender == NULL &  nationality==NULL ~ dataset %>% filter(M.F == gender, Country == nationality),
       
      !age==NULL & !gender == NULL &  nationality==NULL ~ dataset %>% filter(Country == nationality)
       
    )
}

demographics_filter4 <- function(dataset, age=NULL, gender=NULL, nationality=NULL){ #demographic data, dataset = raw data
  ifelse(is.null(age), 
         ifelse(is.null(gender),
                ifelse(is.null(nationality),
                       dataset,
                       dataset %>% filter(Country == nationality)),
                ifelse(is.null(nationality),
                       dataset %>% filter(M.F == gender),
                       dataset %>% filter(Country == nationality, M.F == gender))),
         
         ifelse(is.null(gender),
                ifelse(is.null(nationality),
                       dataset %>% filter(Age == age),
                       dataset %>% filter(Age == age, Country == nationality)),
                ifelse(is.null(nationality),
                       dataset %>% filter(Age == age, M.F == gender),
                       dataset %>% filter(Age == age, Country == nationality, M.F == gender)))
  )
}

demographics_filter5 <- function(dataset, age, gender, nationality){ #demographic data, dataset = raw data
  if(missing(age)) {
    
    if(missing(gender)){
      if(missing(nationality)){
        dataset
      }
      else{
        dataset %>% filter(Country == nationality)
      }
    } else if(missing(nationality)){
      dataset %>% filter(M.F == gender)
    }
    else {
      dataset %>% filter(Country == nationality, M.F == gender)
    }
    
    
    
    
  } else if(missing(gender)){
    if(missing(nationality)){
      dataset %>% filter(Age == age)      
    }
    else{
      dataset %>% filter(Age == age, Country == nationality)
    }
  } else if(missing(nationality)){
    dataset %>% filter(Age == age, M.F == gender)
  }
  else{
    dataset %>% filter(Age == age, Country == nationality, M.F == gender)
  }
}



data_all_dup <- demographics_filter5(data_all, age=28, gender="M")
test <- demographics_filter2(data_all, age = 2, gender = 1, nationality = 1)
test
nationality <- "USA"
age = 25
gender = "M"
dataset <- data_all_dup


data_all_dup <- data_all %>% filter()
dim(data_all_dup)
dim(data_all)
data_all_dup <- data_all %>% filter(Age == age, M.F == gender)
View(data_all_dup)

```
